# Generated by Django 4.0.2 on 2022-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('message', models.TextField()),
                ('date_posted', models.DateField(auto_now=True)),
            ],
        ),
    ]
